services:
  - type: web
    name: chatbot-proxy
    runtime: node
    region: oregon # Change if needed
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 18
